# -*- coding: utf-8 -*-
"""add_elements.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19O3bAplnqGM4sZx_2hIeQo7JNlYLPSOM
"""

# Sum of Corresponding Elements in Two Lists

# Create two lists of equal length containing integers.
var1 = [2,3,4,5,6]
var2 = [7,8,9,0,1]

# Use a `lambda` function with `map()` to add corresponding elements from the two lists.
add_elements = list(map(lambda x,y : x+y, var1, var2))

# Convert the result to a list and print it.
print("Sum of corresponding elements are:", add_elements)

