# -*- coding: utf-8 -*-
"""Countdown_Iterator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1icF91cKRFEBim0cOiP7Rhy8HK6LIUbJ1
"""

# Implement a Countdown Iterator

#Create a class called `CountdownIterator`.
class CountdownIterator:

# Define an `__init__` method to initialize the starting number.
    def __init__(self, start_num):
        self.current_num = start_num

#Implement the `__iter__` method to return the iterator object itself.
    def __iter__(self):
        return self

#Implement the `__next__` method to return the current number and decrement it by one.
    def __next__(self):

#Raise a `StopIteration` exception when the countdown reaches zero.
        if self.current_num < 0:
            raise StopIteration
        value = self.current_num
        self.current_num -= 1
        return value

#Create an instance of `CountdownIterator` with a specific starting number.
countdown = CountdownIterator(5)

#Use a `for` loop or the `next()` function to iterate through the countdown.
for num in countdown:
 print(num)

