# -*- coding: utf-8 -*-
"""dictionary_list.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15xLm_1Um6ibepUSVWfYnTGZmfPjTfdrF
"""

# Given two lists, one containing names and the other containing ages, create a dictionary that maps each name to its corresponding age.

# Create two lists: one for names and one for ages.
names = ["cherry","George","Kylie","Cicil"]
ages = [23,45,32,56]

if len(names) != len(ages):
  print("Not matches")
else:

# Use a loop or dictionary comprehension to iterate over the indices of the lists.
  person_dict = {names[i]: ages[i] for i in range(len(names))}

# Store these key-value pairs in a dictionary.
print(person_dict)

