# -*- coding: utf-8 -*-
"""Ecommerce_system.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JCaG_scx64gCx9bwALOx2HMHW_GSK1ov
"""

# Develop a Simple E-Commerce System
class Product:
  def __init__(self,name, price, stock):
    self.name = name
    self.price = price
    self.stock = stock

  def purchase(self, quantity):
    if quantity <= self.stock:
      self.stock -= quantity
      print(f"Purchased: {quantity} of {self.name}")
      return True
    else:
      print(f"Insufficient stock for {self.name}")
      return False

  def restock(self, quantity):
    self.stock += quantity
    print(f"Restocked: {quantity} of {self.name}")

  def display_info(self):
    print(f"Name: {self.name} Price:{self.price} Stock:{self.stock}")


class Customer:
  def __init__(self, name, customer_id):
    self.name = name
    self.customer_id = customer_id
    self.cart = {}

  def add_to_cart(self, product, quantity):
    if product.stock >= quantity:
      self.cart[product] = self.cart.get(product, 0) + quantity
      print(f"{self.name} added {quantity} of {product.name} to cart.")
    else:
      print(f"Insufficient stock for {product.name}")

  def remove_from_cart(self, product):
    if product in self.cart:
      removed_quantity = self.cart.pop(product)
      print(f"{self.name} removed {removed_quantity} of {product.name} from cart")
    else:
      print(f"{self.name} does not have {product.name} in their cart.")

  def checkout(self):
    print(f"{self.name} is checking out:")
    total = 0
    for product, quantity in self.cart.items():
      if product.purchase(quantity):
       total += product.price * quantity
    print(f"Total amount: {total}")
    self.cart.clear()
    print("Cart cleared.")

# Testing the system.
product1 = Product("Laptop", 50000, 5)
product2 = Product("Phone", 20000, 10)
product3 = Product("Earbuds", 1500, 15)

# Display product info
print("\nInitial Product Info:")
product1.display_info()
product2.display_info()
product3.display_info()

# Create Customer
customer1 = Customer("George", 101)

# Add to cart
customer1.add_to_cart(product1, 1)
customer1.add_to_cart(product2, 2)
customer1.add_to_cart(product3, 3)

# Remove an item
customer1.remove_from_cart(product2)

# Checkout
customer1.checkout()

# Display updated product info
print("\nUpdated Product Info After Checkout:")
product1.display_info()
product2.display_info()
product3.display_info()

