# -*- coding: utf-8 -*-
"""extarct_phone_number.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ezx9TA9sjkxad0q7tsyampv5myu3FKbV
"""

# Extract phone numbers

import re
def extract_phone_numbers(text):
  pattern = r'\(?\d{3}\)?[\s.-]?\d{3}[\s.-]?\d{4}'
  return re.findall(pattern, text)

sample_text = """
Contact us at (123) 456-7890 or 987-654-3210.
Our fax is 123.456.7890 and alternate line is 111 222 3333.
Invalid: 1234567890 or 123-45-6789.
"""

phones = extract_phone_numbers(sample_text)
print("Extracted Phone Numbers:")
for phone in phones:
    print(phone)

