# -*- coding: utf-8 -*-
"""extract_url.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/112AoYC6pvk5jhVm6OnAhZ_Uuslh6i4fN
"""

# Find All URLs in a Text
import re
def find_URL(text):
  pattern = r'https?://\S+|www\.\S+'
  return re.findall(pattern, text)

sample_text = """
Visit our site at https://www.example.com or follow the docs at http://docs.example.com.
You can also check www.testsite.org for more info or go to https://github.com/user/repo.
Invalid: example.com, ftp://example.com
"""

urls = find_URL(sample_text)
print("Extracted URLs:")
for url in urls:
    print(url)

