# -*- coding: utf-8 -*-
"""Fibonacci_iteration.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RSjkcCNa6LQCjNPTM_Geoa5ToPIUUGQ3
"""

# Create an Iterator for Fibonacci Sequence

class FibonacciIterator:
    def __init__(self, max_count):
        self.a = 0
        self.b = 1
        self.count = 0
        self.max_count = max_count  # Total numbers to generate

    def __iter__(self):
        return self

    def __next__(self):
        if self.count >= self.max_count:
            raise StopIteration

        fib_number = self.a
        self.a, self.b = self.b, self.a + self.b
        self.count += 1
        return fib_number

# Generate first 10 Fibonacci numbers
fib_iter = FibonacciIterator(10)

for num in fib_iter:
    print(num)

