# -*- coding: utf-8 -*-
"""Filter_Names.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BCmA6YtqX39h0nPUZm2X608wwAFP9KcD
"""

# Filter Names Starting with a Specific Letter

# Create a list of names
names = ["bob","geoge","rose","vetilda","steve","rebecca","ben","vyom","vanilla"]

# Write function to start with a letter using filter
start = list(filter(lambda x : x.startswith("v"), names))
print(start)

