# -*- coding: utf-8 -*-
"""Library_mgmt.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LuGpluerbEOQYQhb0Vq2Wp_Q6zDgZexm
"""

# Implement a simple library management system with classes for books and members.

# Define a Book Class
class Book:
  def __init__(self,title,author,isbn,availability=True):
    self.title = title
    self.author = author
    self.isbn = isbn
    self.availability = availability

  def borrow_book(self):
    if self.availability:
      self.availability = False
      print(f"Book {self.title} has been borrowed.")
    else:
      print(f"Book {self.title} is not available for borrowing.")

  def return_book(self):
    self.availability = True
    print(f"Book {self.title} has been returned.")

  def display_info(self):
    print(f"Title: {self.title}")
    print(f"Author: {self.author}")
    print(f"ISBN: {self.isbn}")
    print(f"Availability: {'Available' if self.availability else 'Not Available'}")

# Define a Member Class:
class Member:
  def __init__(self,name,member_id):
    self.name = name
    self.member_id = member_id
    self.borrowed_books = []

  def borrow_book(self,book):
    if book.availability:
      book.borrow_book()
      self.borrowed_books.append(book)
    else:
      print(f"{book.title} is not available for borrowing.")

  def return_book(self,book):
    if book in self.borrowed_books:
      book.return_book()
      self.borrowed_books.remove(book)
    else:
      print(f"{book.title} is not borrowed by {self.name}.")

  def display_borrowed_books(self):
    print(f"{self.name} has borrowed:")
    for book in self.borrowed_books:
      book.display_info()


# Create books
book1 = Book("Alice's Adventures in Wonderland", "Lewis Carroll", "1234567890")
book2 = Book("Dracula", "Bram Stoker", "9876543210")

# Create a member
member1 = Member("Rebecca", "M001")

# Borrow and return books
member1.borrow_book(book1)
member1.borrow_book(book2)
member1.display_borrowed_books()

member1.return_book(book1)
member1.display_borrowed_books()

book1.display_info()
book2.display_info()

