# -*- coding: utf-8 -*-
"""palindrome.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xyazbw1ZYOh14sVKaWLd0fl0QnlSq0VO
"""

# Write a function that checks if a given string is a palindrome (reads the same backward as forward). The function should ignore case and spaces.

# Define a function that accepts a string as a parameter.
def palindrome(s):

# Convert the string to lower case to make the check case-insensitive.
  s = s.lower()

# Remove spaces from the string.
  s = s.replace(" ","")

# Compare the cleaned string to its reverse.
  return s == s[::-1]

# Return `True` if the string is a palindrome, otherwise return `False`.
print(palindrome("Madam"))
print(palindrome("Race Car"))
print(palindrome("Knowledge"))

