# -*- coding: utf-8 -*-
"""prime_number.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13MWPSKWrvHxbICM7FpAj6NpCHOepVZof
"""

#Write a function that takes an integer n as input and returns a list of all prime numbers up to n

#Define a function that accepts an integer `n` as a parameter.
def prime_numbers(n):
  prime_numbers = []

# Create a helper function to check if a number is prime.
  def is_prime(n):
    if num <= 1:
      return False
    for i in range(2, int(num**0.5)+1):
      if num % i == 0:
        return False
    return True

# Initialize an empty list for primes
  primes = []

# Loop through numbers and check for prime
  for num in range(2, n + 1):
    if is_prime(num):
      primes.append(num)

# Return the list of prime numbers
  return primes

print(prime_numbers(20))

