# -*- coding: utf-8 -*-
"""replace_date.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GvTrCR1-xmvMm9uk3iV6A3rw4z0fiSce
"""

# Replace Dates in a Text

import re
def replace_dates(text):
  pattern = r'(\d{1,2})/(\d{1,2})/(\d{4})'
  return re.sub(pattern, r'\3-\2-\1', text)

sample_text = """
Today's date is 30/07/2025 and the project started on 07-15-2023.
Another date to note: 01/01/2020.
"""

updated_text = replace_dates(sample_text)
print("Modified Text:\n", updated_text)

