# -*- coding: utf-8 -*-
"""School_management.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15Fhs4WLKHWoBoFbD15yUNxJpwsFYLWRw
"""

# Implement a basic school management system with classes for students and courses.

# Define a `Student` Class
class Student:
  def __init__(self, name, student_id):
    self.name = name
    self.student_id = student_id
    self.enrolled_courses = []

  def enroll(self, course):
    if course.capacity > 0:
      if course not in self.enrolled_courses:
        self.enrolled_courses.append(course)
        course.enrolled_students.append(self)
        course.capacity -= 1
        print(f"{self.name} enrolled in {course.course_name}.")
      else:
        print(f"{self.name} is already enrolled in {course.course_name}.")
    else:
      print(f"Capacity of {course.course_name} is full.")

  def drop(self, course):
    if course in self.enrolled_courses:
      self.enrolled_courses.remove(course)
      course.enrolled_students.remove(self)
      course.capacity += 1
      print(f"{self.name} dropped {course.course_name}.")
    else:
      print(f"{self.name} is not enrolled in {course.course_name}.")


  def display_enrolled_courses(self):
    print(f"{self.name} is enrolled in:")
    if self.enrolled_courses:
      for course in self.enrolled_courses:
        print(f"- {course.course_name} ({course.course_code})")
    else:
      print("No courses enrolled.\n")


class Course:
  def __init__(self, course_name, course_code, capacity):
    self.course_name = course_name
    self.course_code = course_code
    self.capacity = capacity
    self.enrolled_students = []

  def display_info(self):
    print(f"\nCourse: {self.course_name} ({self.course_code})")
    print(f"Available Capacity: {self.capacity}")
    print("Enrolled Students:")
    if self.enrolled_students:
      for student in self.enrolled_students:
        print(f"- {student.name} ({student.student_id})")
    else:
      print("No students enrolled.")


# Test the System
if __name__ == "__main__":
    # Create courses
    math = Course("Mathematics", "MATH101", 2)
    physics = Course("Chemistry", "CHEM101", 1)

    # Create students
    Mathew = Student("Mathew", "S001")
    Jack = Student("Jack", "S002")
    Adam = Student("Adam", "S003")

    # Enroll students
    Mathew.enroll(math)
    Jack.enroll(math)
    Adam.enroll(math)  # Should fail - course is full

    # Enroll in Physics
    Mathew.enroll(physics)
    Jack.enroll(physics)  # Should fail - course is full

    # Display info
    Mathew.display_enrolled_courses()
    Jack.display_enrolled_courses()
    math.display_info()
    physics.display_info()

    # Drop a course
    Mathew.drop(math)
    Adam.enroll(math)  # Now should succeed

    # Final state
    math.display_info()
    Adam.display_enrolled_courses()

