# -*- coding: utf-8 -*-
"""split_text.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TfQRRaScZs-amW4T-2Xygt3xSH5vNgjS
"""

# Split a Text into Sentences

import re
def split_into_sentences(text):
  pattern = r'(?<!\w\.\w.)(?<![A-Z][a-z]\.)(?<=\.|\?|\!)\s'
  return re.split(pattern, text)

sample_text = "Hello! How are you doing? I hope you're enjoying Python. Let's write some code. And Keep practicing."

sentences = split_into_sentences(sample_text)
print("Split Sentences:")
for s in sentences:
    print(f"- {s}")

