# -*- coding: utf-8 -*-
"""Squared_Even.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TF0R2_GqJ2JkweZGSbhMLQk_9OoTdcTX
"""

# Step 1: Create a list of integers
num = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Step 2: Use filter() with a lambda function to get even numbers
even_num = filter(lambda x: x % 2 == 0, num)

# Step 3: Use map() with a lambda function to square the even numbers
squared_even= map(lambda x: x ** 2, even_num)

# Step 4: Convert the result to a list and print it
result = list(squared_even)
print(result)

