# -*- coding: utf-8 -*-
"""squaredeven_comprehension.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WX0g1-HKuNBLF7eUbq7K88OoG-FqkgyI
"""

# Create a list of numbers from 1 to 100.
#Use list comprehension to create a new list that contains the squares of all even numbers from the original list.
x = [x**2 for x in range(1,100) if x % 2 ==0]

# Collect the squared numbers in a new list.
print("New List:", x)

