# -*- coding: utf-8 -*-
"""transform_list.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rfSJ34vJp6wObFy4l5fVqy9HA9_6yo6A
"""

# Filter and Transform a List of Dictionaries

# Create a dictionary having Keys:Values
dict1 = [
    {"name": "Senorita", "age": 25},
    {"name": "Calida", "age": 15},
    {"name": "Pearl", "age": 30}
]

# Use the `filter()` function to select dictionaries from a list where a specific key has a value greater than a given threshold.
transform_data = list(filter(lambda x: x['age'] > 20, dict1))

# Use the `map()` function to transform the selected dictionaries by extracting certain keys.
names = list(map(lambda x: x['name'], transform_data))

# Print the values
print("Transformed data(age > 20):", transform_data)
print("Names are:", names)