# -*- coding: utf-8 -*-
"""Upperase_strings.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11zDWTGpdzyaPk9yHFeFZ8s6ORBceeq3R
"""

#Convert List of Strings to Uppercase

# Create the list of names
names = ["bob","geoge","rose","vetilda","steve","rebecca","ben","vyom","vanilla"]

# Write a map function to convert to upper case.
upper_case_names = list(map(lambda x : x.upper(), names))
print(upper_case_names)

