# -*- coding: utf-8 -*-
"""Vaildate_Email.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ezx9TA9sjkxad0q7tsyampv5myu3FKbV
"""

# Write a regular expression to validate email addresses.
import re
def validate_email(email):
  pattern = r"^[A-Za-z0-9-._]+@[A-za-z0-9-]+\.[A-Za-z0-9-.]+$"
  return re.match(pattern,email) is not None

# test emails
test_emails = [
    "local-part@domain.com",
    "abcd.doe@example.co.in",
    "user@domain",
    "test.email+-.@sign.com",
    "john123@gmail.com",
    "invalid-email.com"

]

for email in test_emails:
    result = "Valid" if validate_email(email) else "Invalid"
    print(f"{email}: {result}")

